fix help&support page responsiveniss solves issue #7268
opencollective/opencollective-frontend pull request #10266
Opened 2024-04-08 16:02 UTC by MarwanBz

Resolve [https://github.com/opencollective/opencollective/issues/7268]

# Description
this fixes the raised issue about the responsiveness help&support page on approximately 850px or less devices  

# Screenshots
![chrome-capture-2024-4-8 (1)](https://github.com/opencollective/opencollective-frontend/assets/69892218/38d23cb0-6109-45cb-b51a-25697b9202c7)

2024-04-09 07:08 UTC, Betree requested changes
Hi @MarwanBz, thanks for your contribution! Some feedback below.

- The "Get to Know Us" still has truncated text on some resolutions
![image](https://github.com/opencollective/opencollective-frontend/assets/1556356/684893cc-61db-4f07-8a49-466a7914511d)

- There is a regression on widescreen, the topics are overlapping each other because the width is too narrow
![image](https://github.com/opencollective/opencollective-frontend/assets/1556356/699036a7-2f4c-451d-b295-9d3ee4324722)

2024-04-09 07:08 UTC, Betree commented on components/help-and-support/BrowseTopicSection.js
> +          gridTemplateColumns={[null, 'repeat(2, 288px)', 'repeat(2, 300px)','repeat(3, 272px)', null, `repeat(3, 320px)`]}
We only support [4 breakpoints](https://github.com/opencollective/opencollective-frontend/blob/0868babd6bbd5a667bc11dc75340a77c316804d1/lib/theme/breakpoints.ts). So only the 4 first values will be considered. The `1020px` in there was already unnecessary, but with the addition of `750px` we're not considering `null` anymore, which disabled the fixed width and is likely the root cause for the missing gap reported above.

2024-04-09 07:08 UTC, Betree commented on components/help-and-support/BrowseTopicSection.js
> +          width={[null, '568px','750px', '864px', null, '1020px']}
Same here, only the 4 first values will be considered

2024-04-10 06:19 UTC, MarwanBz commented
thanks for the feedback @Betree!
 I really appreciate you taking the time to review my code, and 
I'll make the changes you suggested.

2024-07-05 12:52 UTC, Betree commented
Any updates on this one?

2025-04-07 07:52 UTC, Betree commented
Already resolved in https://github.com/opencollective/opencollective-frontend/pull/10614

2025-04-07 07:52 UTC, closed without merging