Request to be removed as admin
opencollective/opencollective-frontend pull request #4868
Opened 2020-08-18 20:45 UTC by JoyLubega

Resolve opencollective/opencollective/issues/3141

# Description

This PR helps an admin to request other admins to remove them as an admin

# Screenshots

<img width="856" alt="Screenshot 2020-08-18 at 20 13 11" src="https://user-images.githubusercontent.com/29824008/90563650-ddcc4e00-e1ac-11ea-924b-6346b305efd6.png">

2020-08-25 07:15 UTC, Betree requested changes
Hi @JoyLubega, this is a good start but we can't merge a partial feature without the API bindings.

2020-08-25 07:27 UTC, JoyLubega commented
> Hi @JoyLubega, this is a good start but we can't merge a partial feature without the API bindings.

Yes @Betree  I am working on creating a  PR In the API that sends an email whenever that button is clicked. 
Is what you meant?

2020-08-25 08:23 UTC, Betree commented
@JoyLubega Yes

2020-09-15 06:14 UTC, Betree commented on components/edit-collective/sections/Members.js
> +const sendEmailToAdminsMutation = gql`
It could be nice indeed, one option is to add a `askSelfRemoval` boolean param on the `editCoreContributorsMutation` endpoint.

2020-09-15 10:55 UTC, JoyLubega commented on components/edit-collective/sections/Members.js
> +const sendEmailToAdminsMutation = gql`
@Betree I have seen another challenge. `editCoreContributorsMutation` is in V1 yet you advised me from the Api to use V2. I don't see `editCoreContributorsMutation` in V2.
So I am thinking I move `editCoreContributorsMutation` to V2. Would that be a problem

2020-09-18 08:55 UTC, Betree commented on components/edit-collective/sections/Members.js
> +const sendEmailToAdminsMutation = gql`
If you're re-using the existing mutation it's fine to not move to V2. Using V2 is only a requirement when implementing new endpoints.

2020-11-30 14:44 UTC, Betree commented
See https://github.com/opencollective/opencollective-api/pull/4516#issuecomment-735827975

2020-11-30 14:44 UTC, closed without merging