enhancement(OnBoardingModal): improve github url RegExp
opencollective/opencollective-frontend pull request #5649
Opened 2021-01-01 13:13 UTC by Yetizone

Resolve #3507

# Description

Hello, newcomer here. This PR continues the work in https://github.com/opencollective/opencollective-frontend/pull/5247
The new regex allows inputs like `xx` and `xx/qq` but not `xx/qq/zz`.
The coding style changes were automatically added when committing. 
Let me know if there's anything else that needs to be done :) 

# Screenshots
![Screenshot from 2021-01-01 15-10-02](https://user-images.githubusercontent.com/43905913/103439224-c49bd980-4c43-11eb-98b1-63238c42ca90.png)
![Screenshot from 2021-01-01 15-10-12](https://user-images.githubusercontent.com/43905913/103439227-c82f6080-4c43-11eb-823f-43de766f6a07.png)
![Screenshot from 2021-01-01 15-10-27](https://user-images.githubusercontent.com/43905913/103439229-cb2a5100-4c43-11eb-969a-643c1320cec9.png)
![Screenshot from 2021-01-01 15-11-04](https://user-images.githubusercontent.com/43905913/103439231-cebdd800-4c43-11eb-8c0b-5dcb55c28d9c.png)

2021-01-01 23:56 UTC, SudharakaP commented on components/onboarding-modal/OnboardingModal.js
> +      matches(
@Yetizone : Minor simplification, I think you can remove the `=== false` and negate the condition `!matches(...`

2021-01-02 06:39 UTC, SudharakaP requested changes
The new regex seems to have some problems I think. 🤔 

- It doesn't seem to match urls which has a `.` in them. So the example in the issue; `citizenspring/playstreets.brussels` isn't a valid string it seems. 

- GitHub allows the creation of repos with underscore `_`. But the new regex doesn't seem to allow this kinda names. So an example would be something like `playstreets_brussels`. 

- GitHub allows the creation of repos such as `playstreets--brussels` (with two `-` signs) but that doesn't seem to be supported by the regex as well. Single `-` works well.

2021-01-02 12:43 UTC, Yetizone commented
Finished tweaking the regex to allow those repo names.

2021-01-02 20:15 UTC, SudharakaP approved these changes
Seems all fine to me now 👍🏽

2021-01-06 09:04 UTC, Betree approved these changes
Looking good, nice job @Yetizone!

2021-01-06 10:08 UTC, merged