retchQueries after adding funds
opencollective/opencollective-frontend pull request #5775
Opened 2021-01-25 22:48 UTC by JoyLubega

Resolve https://github.com/opencollective/opencollective/issues/3851

# Description

This PR adds functionality for refreshing transactions in the budget section

2021-01-26 10:17 UTC, znarf requested changes
I haven't tested but.

- Fix lint
- Remove edit to package-lock.json
- Make sure to pass `API_V2_CONTEXT` to `budgetSectionQuery`

2021-01-26 20:25 UTC, JoyLubega commented
Hey @znarf  I added a PR for the api https://github.com/opencollective/opencollective-api/pull/5187 basing on the specs added. I have also made some changes here. thanks

2021-01-27 09:14 UTC, znarf commented on components/host-dashboard/AddFundsModal.js
> +      { query: collectivePageQuery, variables: { slug: collective.slug } },
Would be great to also use `getCollectivePageQueryVariables` here.

2021-01-27 09:14 UTC, znarf commented on components/host-dashboard/AddFundsModal.js
> +        variables: getBudgetSectionQueryVariables(collective.slug),
Nice!

2021-01-27 09:16 UTC, znarf requested changes
Looks good! Just one last thing to address.

2021-01-27 09:18 UTC, JoyLubega commented
> Looks good! Just one last thing to address.

Thanks. Let me add `getCollectivePageQueryVariables`  now

2021-01-27 09:56 UTC, znarf requested changes
package-lock.json should not be changed

2021-01-27 09:57 UTC, JoyLubega commented
> package-lock.json should not be changed

yeahhh fixed it. I rebased and it showed changes. I have reverted

2021-01-27 10:16 UTC, JoyLubega commented
@znarf I have made the changes

2021-01-27 14:17 UTC, znarf approved these changes
@Betree good for you too?

2021-01-27 15:09 UTC, merged

2021-01-28 09:27 UTC, Betree reviewed
Yep that looks good!