Revising text and language throughout the app
opencollective/opencollective-frontend pull request #5798
Opened 2021-01-28 07:49 UTC by alanna

Work in progress.

Attempting award for most files changed in one pull request. 👺

2021-01-29 08:37 UTC, znarf requested changes
All tests are failing so someone will need to dig into it.

2021-01-29 08:41 UTC, znarf commented
First one is to run `npm run lint:quiet` or `npm run lint:fix` for the syntax issues. It's for example forbidden to a have single quote in a middle of string between single quotes. Usually, put the string between special quotes (instead of single quotes), this one: `

2021-02-03 00:40 UTC, alanna commented
@znarf what do we need to do in order to merge this? I'm concerned it's going to get out of date with subsequent updates to the repo.

2021-02-03 21:56 UTC, alanna commented
@znarf I think I fixed all the single quotes. Let me know if there's anything else needed.

2021-02-04 12:10 UTC, znarf commented on components/discover/DiscoverCollectiveCard.js
> +                defaultMessage="{count, plural, one {contributor {prettyCount} } {Financial contributors {prettyCount} }}"
`other` is a keyword, not a a string that will appear for the user

2021-02-04 12:49 UTC, znarf commented
I moved to a cleaner branch with a bunch of fixes but we're not there yet:
https://github.com/opencollective/opencollective-frontend/pull/5834

2021-02-05 06:34 UTC, SudharakaP commented on components/CreateOrganizationForm.js
> +    defaultMessage: 'Enter valid a website, e.g. www.example.com or example.org',
I think should be; 

```suggestion
    defaultMessage: 'Enter a valid website, e.g. www.example.com or example.org',
```

2021-02-05 06:34 UTC, SudharakaP commented on components/DefinedTerm.js
> +      'A Fiscal Host is an entity that holds the money on behalf of a Collective, and taxes care of accounting, taxes, and invoices.',
```suggestion
      'A Fiscal Host is an entity that holds the money on behalf of a Collective, and takes care of accounting, taxes, and invoices.',
```

2021-02-05 13:34 UTC, znarf commented
@SudharakaP for your feedback, can you share your comments on the latest PR?

https://github.com/opencollective/opencollective-frontend/pull/5834

2021-02-05 13:34 UTC, closed without merging