Update Nextjs to 10.1.3 (Experiment)
opencollective/opencollective-frontend pull request #6170
Opened 2021-04-13 17:56 UTC by SudharakaP

I am opening this PR to try out updating Nextjs to 10.1.3. I have a doubt that the `package-lock.json` isn't correctly updated by dependabot in https://github.com/opencollective/opencollective-frontend/pull/6149. 🤔

2021-04-13 18:23 UTC, SudharakaP commented
@znarf : Seems my doubt is correct. Are you okay with merging this one? 😄

2021-04-14 06:51 UTC, znarf requested changes
There seems to be a conflict with package-lock.json.

2021-04-14 08:03 UTC, SudharakaP commented
> There seems to be a conflict with package-lock.json.

@znarf : The conflict is resolved. It should be good now. 👍🏽

2021-04-14 12:52 UTC, znarf approved these changes

2021-04-14 12:52 UTC, znarf approved these changes

2021-04-14 12:53 UTC, merged