fix (footer): don't show login and signup links for a logged in user
opencollective/opencollective-frontend pull request #6372
Opened 2021-05-17 09:37 UTC by akashgp09

Resolve [#4235](https://github.com/opencollective/opencollective/issues/4235)

# Description

Used the **LoggedInUser** object to check if a user is logged in or not and accordingly display the signup and login links in the footer

# Screenshots

![Screenshot from 2021-05-17 15-02-36](https://user-images.githubusercontent.com/55311336/118467182-37a07b00-b721-11eb-8ed9-435015f5bf34.png)

2021-05-17 11:53 UTC, Betree requested changes
Thanks for starting this @akashgp09 :raised_hands:

2021-05-17 11:53 UTC, Betree commented on components/CreateEvent.js
> +        <Footer LoggedInUser={LoggedInUser} />
Passing this as a prop each time we use `Footer` is tedious and easy to miss when implementing new pages. We should rather use the `useUser` hook: https://github.com/opencollective/opencollective-frontend/blob/8bbb7cdc1c12770c4e73173147ebc4224d5c95bf/components/UserProvider.js#L162

2021-05-17 11:53 UTC, Betree commented on components/Footer.js
> +    navigation.platform = {
`navigation` is a shared constant, it should not be mutated

2021-05-31 13:24 UTC, Betree commented
@akashgp09 Can I help with this one?

2021-05-31 13:32 UTC, akashgp09 commented
sure @Betree , I'm a bit busy these weeks you can take this one : ). sorry I left it unfinished

2021-05-31 13:43 UTC, Betree commented
No problem, I'm closing for now in case someone else has the time to look at it. Feel free to re-open if you want to give it a second look

2021-06-15 06:22 UTC, akashgp09 commented
Hi @Betree I am free now and ready to contrinue working on this. Please re-open it  :)

2021-06-15 10:54 UTC, Betree approved these changes
Perfect!

2021-06-15 12:07 UTC, merged