Add Support for Admins to Contribute to Past Events
opencollective/opencollective-frontend pull request #6797
Opened 2021-08-27 18:59 UTC by SudharakaP

Resolve https://github.com/opencollective/opencollective/issues/3982

Requires: https://github.com/opencollective/opencollective-api/pull/6511 

Related to https://github.com/opencollective/opencollective-frontend/pull/6795

https://user-images.githubusercontent.com/12435965/131178317-71fa43f5-f50a-41ed-ab1a-6b50f2f5bc2e.mp4

2021-08-28 07:53 UTC, znarf commented on lib/collective-sections.js
> +      return (collective.type === CollectiveType.COLLECTIVE || collective.type === CollectiveType.EVENT) && isAdmin;
`FUND` and `PROJECT` also.

Maybe even all `type`s in the future, but not for now.

2021-08-28 07:54 UTC, znarf commented on components/collective-page/sections/Contribute.js
> +      (collective.isActive && !isPastEvent(collective)) || (collective.type === CollectiveType.EVENT && isAdmin);
```suggestion
      (collective.isActive && (!isPastEvent(collective) || isAdmin));
```

2021-08-29 14:24 UTC, SudharakaP commented
@znarf : Thanks for the reviews. I've done the changes based on those. 👍🏽

2021-08-30 18:37 UTC, SudharakaP commented
@znarf : Just to note, as per Ben's suggestion here; https://opencollective.slack.com/archives/C020ZQSLM5M/p1630321759013100?thread_ts=1630091991.008600&cid=C020ZQSLM5M I've added a small warning to show for past events. Here's a screencast which show the contribution flow for a past event and a regular event; 

![past event warning](https://user-images.githubusercontent.com/12435965/131388048-a9c60f84-34ae-4e9a-aa78-cc9f9f8ac959.gif)

2021-08-30 18:54 UTC, znarf requested changes

2021-08-30 18:54 UTC, znarf commented on lib/collective-sections.js
> +          collective.type === CollectiveType.PROJECT) &&
Please use a more elegant syntax, use `includes`.

2021-08-30 18:54 UTC, znarf commented on components/contribution-flow/index.js
> +    defaultMessage: `You're contributing to a past event`,
```suggestion
    defaultMessage: `You're contributing to a past event.`,
```

2021-08-30 20:58 UTC, SudharakaP commented on lib/collective-sections.js
> +          collective.type === CollectiveType.PROJECT) &&
Done. 👍🏽

2021-09-01 19:00 UTC, znarf approved these changes
Good for me. Next step would be to get team feedback and see if we can remove this restriction for non-admins too. But make sure to disable ticket buying for sure.

2021-09-01 19:04 UTC, SudharakaP commented
> Good for me. Next step would be to get team feedback and see if we can remove this restriction for non-admins too. But make sure to disable ticket buying for sure.

@znarf : Thanks for the feedback. I'll be merging this today then. As for allowing it for non-admins (without ticket buying), I'll create another issue and then we'll discuss in tomorrow standup. 👍🏽

2021-09-01 19:23 UTC, merged

2021-09-01 20:12 UTC, SudharakaP commented
> @znarf : Thanks for the feedback. I'll be merging this today then. As for allowing it for non-admins (without ticket buying), I'll create another issue and then we'll discuss in tomorrow standup. 👍🏽

And the issue is created at, https://github.com/opencollective/opencollective/issues/4617