Change fontstyle of Labels and order of Datepicker
opencollective/opencollective-frontend pull request #7386
Opened 2022-01-25 20:56 UTC by JoyLubega

Resolve https://github.com/opencollective/opencollective/issues/4900

# Description

- [ ] Change order

- [ ] Change label style

# Screenshots

<img width="854" alt="Screenshot 2022-01-25 at 11 42 03 PM" src="https://user-images.githubusercontent.com/29824008/151058249-d2c94b4e-ba2d-46df-8efb-851ff13da106.png">

2022-01-26 06:48 UTC, SudharakaP requested changes
@JoyLubega : Thanks much for the contributions. 😄 

Some minor feedback, double checking the design. Also note that the `Reset` and `Apply` button font size should be `14px` which means we have to change the `buttonSize` prop to `medium` I think. 😉

2022-01-26 06:48 UTC, SudharakaP commented on components/budget/filters/PeriodFilter.js
> +            labelFontSize="13px"
According to design; 

```suggestion
            labelFontSize="16px"
```

2022-01-26 06:48 UTC, SudharakaP commented on components/budget/filters/PeriodFilter.js
> +                buttonProps={{ p: 1, fontSize: '11px' }}
According to design,

```suggestion
                buttonProps={{ p: 1, fontSize: '13px', fontWeight: 400 }}
```

2022-01-26 09:43 UTC, JoyLubega commented
<img width="1440" alt="Screenshot 2022-01-26 at 12 39 13 PM" src="https://user-images.githubusercontent.com/29824008/151139774-61db7cb3-719d-44d4-b940-2086f5a53c07.png">

@SudharakaP  I made the changes, 14px for buttons make them way too bigger.

2022-01-28 08:26 UTC, Betree commented
> > @SudharakaP I made the changes, 14px for buttons make them way too bigger.
> 
> @Betree : Do you think this is too big? For me it looks okay. thinking

I haven't inspected the styles, but the screenshot seems to match the design

2022-01-28 08:53 UTC, SudharakaP approved these changes

2022-01-28 08:58 UTC, merged