Make Country Filter Searchable by Country name and Country Code
opencollective/opencollective-frontend pull request #7745
Opened 2022-04-29 19:52 UTC by SudharakaP

Related to the discussion at, https://opencollective.slack.com/archives/C035S573ZD2/p1651208558348219

2022-04-30 08:00 UTC, znarf requested changes
That looks like a really complicated solution.

What prevent us to search in the label instead?

2022-05-02 21:57 UTC, SudharakaP commented
> That looks like a really complicated solution.
> 
> What prevent us to search in the label instead?

Yes the issue was that the select drop-down (which uses [`react-select`](https://react-select.com/home)) searches by the `value` attribute of the options. The `label` is an internationalized object so I don't think there's an easy way to search for that. However in the DB we store by country code; so we needed a conversion from the country to country code which I was trying to avoid. 

However thinking further I simplified the code by creating a country to country code map at, https://github.com/opencollective/country-currency-emoji-flags/pull/3. This will make sure we can pass the correct country code to the API.

2022-05-03 14:16 UTC, SudharakaP commented
@znarf : Sorry, seems there's a much more simpler solution to this using the [`customFilter`](https://react-select.com/advanced#custom-filter-logic) in `react-select`. I've refactored this code to use that.

2022-05-10 07:41 UTC, znarf reviewed
Could you add an example in Storybook so we can easily test the behavior?

> Make Country Filter Searchable by Country name and Country Code

I don't see how it's searching in the code. What's contained in `data.country`?

If it's replacing something that existed before, I don't see deleted code in this PR. Was it relying on the default `filterOption`?

2022-05-10 07:53 UTC, SudharakaP commented
> Could you add an example in Storybook so we can easily test the behavior?
> 
> > Make Country Filter Searchable by Country name and Country Code
> 
> I don't see how it's searching in the code. What's contained in `data.country`?
> 
> If it's replacing something that existed before, I don't see deleted code in this PR. Was it relying on the default `filterOption`?

@znarf : Since we have removed the country code from this country input list, I don't think there's any requirement to search by country code. The original slack thread; https://opencollective.slack.com/archives/C035S573ZD2/p1651208558348219 is about searching by country name. It's my mistake that I wrote `Make Country Filter Searchable by Country name and Country Code` in the PR title. It should be `Make Country Filter Searchable by Country name`. 

As for the example in storybook, we already have one at, https://styleguide.opencollective.com/?path=/story/design-system-inputtypecountry--default-story.

2022-05-10 12:02 UTC, znarf commented
Thank you.

If I test here, the search doesn't work:
https://opencollective-styleguide-n45yn6xtf-opencollective.vercel.app/?path=/story/design-system-inputtypecountry--default-story

2022-05-10 12:03 UTC, znarf commented on components/InputTypeCountry.js
> +      return candidate.data.country?.toLowerCase()?.includes(input);
if the goal is to have a case insensitive search, why are you not lowercasing the input?

2022-05-10 13:17 UTC, SudharakaP commented
> Thank you.
> 
> If I test here, the search doesn't work: https://opencollective-styleguide-n45yn6xtf-opencollective.vercel.app/?path=/story/design-system-inputtypecountry--default-story

I've corrected the problem mentioned above, https://github.com/opencollective/opencollective-frontend/pull/7745#discussion_r869222458 and it's working. Here's a screen-cast for the preview; https://opencollective-styleguide-git-fix-make-co-c752a2-opencollective.vercel.app/?path=/story/design-system-inputtypecountry--default-story

![search-country](https://user-images.githubusercontent.com/12435965/167637352-2157066c-a169-426e-8191-0f78f6b4225a.gif)

2022-05-16 12:41 UTC, BenJam commented
boop! is this okay?

2022-05-16 13:52 UTC, znarf approved these changes
Good to go.

2022-05-16 18:25 UTC, merged