Remove older `TopBar` in favor of `TopBarV2`
opencollective/opencollective-frontend pull request #7850
Opened 2022-06-01 19:46 UTC by SudharakaP

Resolve https://github.com/opencollective/opencollective/issues/5610

2022-06-03 08:55 UTC, Betree requested changes
Let's wait to have a team consensus on the new top bar before merging & deploying that

2022-06-21 14:32 UTC, SudharakaP commented
> Let's have a PR to activate it for everyone first.

@znarf : Done at, https://github.com/opencollective/opencollective-frontend/pull/7920

2022-06-28 15:38 UTC, znarf approved these changes

2022-06-28 15:38 UTC, znarf commented
Looks good to me.

2022-06-28 17:48 UTC, merged