Add reset button for Payee Step
opencollective/opencollective-frontend pull request #8366
Opened 2022-11-06 15:50 UTC by JoyLubega

Resolve: [opencollective/opencollective/issues/4840](4840)

# Description
This PR adds a Reset button on the Payee step when creating an expense.

# Screenshots
<img width="756" alt="Screenshot 2022-11-06 at 4 49 09 PM" src="https://user-images.githubusercontent.com/29824008/200180635-67434fd1-091a-4d5a-a9f2-72bba847ca8d.png">
<img width="716" alt="Screenshot 2022-11-06 at 4 49 18 PM" src="https://user-images.githubusercontent.com/29824008/200180637-21b90709-5a37-47c3-bb48-d25b8558172f.png">

2022-11-08 14:12 UTC, Betree commented
@SudharakaP Do you want to review this one?

2022-11-08 14:12 UTC, Betree commented on components/expenses/ExpenseForm.js
> +    id: 'ExpenseForm.ConfirmClearExpenseForm',
Let's keep these as they were, IDs are optional and adding them will invalidate all the current translations for these strings

2022-11-09 17:17 UTC, SudharakaP requested changes
Looks good. There were some minor issue I saw especially the alignment of the `back` and `next` buttons in the payee screen.

2022-11-09 17:17 UTC, SudharakaP commented on components/expenses/ExpenseForm.js
> +  };
Minor suggestion: I am wondering the usefulness of these two functions, they are both used only ones and thus I would say maybe we can just use these functions inline within the `ExpenseFormPayeeStep`;

```
...
handleClearPayeeStep={() => setShowResetModal(true)}
...
```

2022-11-09 17:17 UTC, SudharakaP commented
> @SudharakaP Do you want to review this one?

Sorry, this was in my queue and somehow with other stuff I was late. 😢

2022-11-12 20:41 UTC, JoyLubega commented
@SudharakaP i have made the changes

2022-11-20 15:27 UTC, JoyLubega commented
@Betree  can I have another review in this

2022-11-24 17:48 UTC, SudharakaP approved these changes
I've tested this and all looks good. 💯 

@Betree : We are good to merge if no objections.

2022-12-05 13:06 UTC, Betree approved these changes
Works for me!


@SudharakaP thanks for taking care of the review

2022-12-05 13:07 UTC, merged