enhancement: force contributors to provide a name
opencollective/opencollective-frontend pull request #9193
Opened 2023-08-12 08:28 UTC by criticalAY

Resolve ... 
Require ... 

# Description
Marking the name field as required when making a contribution as guest

Fixes: https://github.com/opencollective/opencollective/issues/6927

# Screenshots
![image](https://github.com/opencollective/opencollective-frontend/assets/48384865/21c4098f-d0e4-4695-a9bf-7074790694bc)

2023-08-12 08:29 UTC, criticalAY commented
I would like to know if I have to update the strings by myself or if the maintainers do it. And if I have to do it myself that what is the process.

2023-08-24 07:24 UTC, Betree requested changes
We want to enforce that only for event tickets, not all contributions

2023-10-09 09:19 UTC, Betree commented
@criticalAY Any progress on that one?

2023-10-09 09:20 UTC, Betree commented
> I would like to know if I have to update the strings by myself or if the maintainers do it. And if I have to do it myself that what is the process.

After updating the string, you need to run `npm run build:langs` to update the language files

2023-10-09 09:39 UTC, criticalAY commented
I will fix it (busy at the moment)

2023-10-10 12:24 UTC, Betree commented
> I will fix it (busy at the moment)

No problem! Just let us know if you don't feel like completing it, it's ok to drop an issue if you don't have the bandwidth to work on it anymore :slightly_smiling_face:

2023-10-19 18:38 UTC, criticalAY commented
Hey I have added the functionality sorry for the delay I caused

2023-10-20 09:52 UTC, criticalAY commented on components/contribution-flow/StepProfileGuestForm.js
> +          )
There is an error when running the command in terminal

2023-10-20 09:52 UTC, criticalAY commented on components/contribution-flow/StepProfileGuestForm.js
> +          )
Something related to other file that I didn't even change

2023-10-20 11:30 UTC, criticalAY commented
Hey! If it's possible to extract the strings using a workflow then please I would like that otherwise I would set up a linux on my system specially for this

2023-10-23 06:37 UTC, Betree commented
@criticalAY Our codebase doesn't officially support Windows, though we'd be happy to merge any solution you have to this problem. Otherwise, we can run the command ourselves on the PR; just let me know if you want to do it that way.

2023-10-23 06:42 UTC, Betree reviewed
There's an issue in the proposed solution, mostly because the specs were not very explicit: `name` is your public name, the one displayed on the platform for your contribution. We don't want to enforce it because it's ok for people to contribute without displaying their real name to everyone.

So the field we really want to enforce is `legalName`, and therefore the fix should be in the `contributionRequiresLegalName` helper.

2023-10-31 07:34 UTC, criticalAY commented
> There's an issue in the proposed solution, mostly because the specs were not very explicit: `name` is your public name, the one displayed on the platform for your contribution. We don't want to enforce it because it's ok for people to contribute without displaying their real name to everyone.
> 
> So the field we really want to enforce is `legalName`, and therefore the fix should be in the `contributionRequiresLegalName` helper.

Done

2023-11-07 11:57 UTC, Betree reviewed
Looking good! We just need to cleanup `components/contribution-flow/StepProfileGuestForm.js`, there's a leftover there (see CI results)

2023-11-08 08:31 UTC, Betree approved these changes

2023-11-08 08:42 UTC, Betree commented
Linter is still failing, see https://github.com/opencollective/opencollective-frontend/actions/runs/6789314258/job/18474100699?pr=9193#step:4:23

2023-11-08 12:53 UTC, criticalAY commented
> Linter is still failing, see https://github.com/opencollective/opencollective-frontend/actions/runs/6789314258/job/18474100699?pr=9193#step:4:23

I ran the lint fix this time it will not fail now

2023-11-09 10:10 UTC, Betree commented
Thanks, merging now!

2023-11-09 10:10 UTC, merged