NavBar: incorrect title and icon
opencollective/opencollective-frontend pull request #9728
Opened 2023-12-08 14:56 UTC by Guilherme-NL

Resolve https://github.com/opencollective/opencollective/issues/7058

# Description

The info component (with apply and actions options) had `width: 100%`, compressing the element that displayed the title and icons. To resolve this, we set the width of this element to auto and applied `justify-content: space-between` to separate the elements.

# Screenshots
![image](https://github.com/opencollective/opencollective-frontend/assets/102393263/40b4e0d9-3d00-4f52-abc0-7f2565b6f62b)
![image](https://github.com/opencollective/opencollective-frontend/assets/102393263/7f0702c5-748b-445c-b59f-f72667e77a04)

2024-01-17 08:08 UTC, Betree requested changes
This breaks the navbar layout, see [here](https://opencollective-frontend-git-fork-guilherm-228657-opencollective.vercel.app/captainfact_io) for example

![image](https://github.com/opencollective/opencollective-frontend/assets/1556356/a8439fb6-216d-4f6c-bae4-c64d6dbdba24)

2024-01-29 15:17 UTC, Betree commented
@Guilherme-NL Any update on this?

2024-02-28 11:56 UTC, Guilherme-NL commented
Hi @Betree, I tried to see this break on the navbar, but everything is okay here!
![image](https://github.com/opencollective/opencollective-frontend/assets/102393263/e9687fd0-d47a-4da2-b0cf-c34cc175b8f1)

2024-07-05 12:53 UTC, Betree commented
Any updates on this one?

2024-07-23 16:04 UTC, Guilherme-NL commented
@Betree, done!

2025-07-29 07:49 UTC, Betree commented
Updated with `main`, we need to make sure this doesn't reintroduce the issue solved by https://github.com/opencollective/opencollective-frontend/pull/10650.

2025-07-29 09:09 UTC, merged